=== marcospont/php2go/tags/RELEASE_0_5_8/docs/dtd/php2go_reports.dtd
<!-- This file is the document type specification for the PHP2Go reports API. -->
<!-- $Id$ -->
<!ENTITY % boolean "( T | F )">
<!ENTITY % identifier "NMTOKEN">
<!ENTITY % word "NMTOKEN">
<!ENTITY % number "CDATA">
<!ENTITY % text "CDATA">
<!ENTITY % colname "NMTOKENS">
<!ENTITY % align "( left | center | right )">
<!ENTITY % mask "( DIGIT | INTEGER | FLOAT | CURRENCY | CPFCNPJ | DATE | TIME | URL | EMAIL | WORD | ZIP | STRING )">
<!ENTITY % pagingstyle "( REPORT_PAGING_DEFAULT | REPORT_PREVNEXT | REPORT_FIRSTPREVNEXTLAST )">
<!ENTITY % events "( onChangePage | onSort | onSearch )">
<!ELEMENT report ( layout?, variable*, datasource, datafilters? )>
<!ATTLIST report
	title %text; #IMPLIED
	baseuri %text; #IMPLIED
	debug %boolean; #IMPLIED
>
<!ELEMENT layout ( pagination?, style?, listener*, icon*, columns? )>
<!ATTLIST layout
	grid %boolean; "F"
	numcols %number; "1"
	printable %boolean; "F"
	pagebreak %number; #IMPLIED
	sortable %boolean; "T"
	emptytemplate %boolean; "T"
	emptyblock %word; #IMPLIED
>
<!ELEMENT pagination ( param* )>
<!ATTLIST pagination
	pagesize %number; "30"
	visiblepages %number; "10"
	style %pagingstyle; "REPORT_PAGING_DEFAULT"
>
<!ELEMENT style EMPTY>
<!ATTLIST style
	link %text; #IMPLIED
	filter %text; #IMPLIED
	button %text; #IMPLIED
	title %text; #IMPLIED
	header %text; #IMPLIED
	altstyle %text; #IMPLIED
	highlight %text; #IMPLIED
	help %text; #IMPLIED
>
<!ELEMENT listener ( #PCDATA )>
<!ATTLIST listener
	event %events; #REQUIRED
	action %text; #IMPLIED
>
<!ELEMENT icon EMPTY>
<!ATTLIST icon
	name %word; #REQUIRED
	path %text; #REQUIRED
>
<!ELEMENT variable EMPTY>
<!ATTLIST variable
	name %word; #REQUIRED
	default %text; #IMPLIED
	searchorder %word; #IMPLIED
>
<!ELEMENT columns ( column* )>
<!ATTLIST columns
	sizes %text; #IMPLIED
	group %colname; #IMPLIED
	groupdisplay %colname; #IMPLIED
>
<!ELEMENT column EMPTY>
<!ATTLIST column
	name %colname; #REQUIRED
	alias %text; #IMPLIED
	help %text; #IMPLIED
	align %align; #IMPLIED
	hidden %boolean; #IMPLIED
	sortable %boolean; #IMPLIED
>
<!ELEMENT datasource ( procedure | ( fields, tables, clause?, groupby?, orderby?, limit? ) )>
<!ATTLIST datasource
	connection %identifier; #IMPLIED
	optimizecount %boolean; #IMPLIED
>
<!ELEMENT procedure ( #PCDATA )>
<!ATTLIST procedure
	cursorname %word; #IMPLIED
>
<!ELEMENT fields ( #PCDATA )>
<!ELEMENT tables ( #PCDATA )>
<!ELEMENT clause ( #PCDATA )>
<!ELEMENT groupby ( #PCDATA )>
<!ELEMENT orderby ( #PCDATA )>
<!ELEMENT datafilters ( datafilter+ )>
<!ELEMENT datafilter EMPTY>
<!ATTLIST datafilter
	field %colname; #REQUIRED
	label %text; #REQUIRED
	mask %mask; #IMPLIED
>
<!ELEMENT param EMPTY>
<!ATTLIST param
	name %word; #REQUIRED
	value %text; #REQUIRED
>

=== marcospont/php2go/branches/dev/examples/resources/report.projects.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : report.projects.xml, used at crudcomponents.example.php -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_reports.dtd">
<report title="Projects List" baseuri="~PHP_SELF~?action=list">
	<!-- layout settings -->
	<layout grid="T" emptytemplate="F">
		<!-- pagination settings: style, style parameters -->
		<pagination style="REPORT_FIRSTPREVNEXTLAST">
			<param name="useButtons" value="T"/>
			<param name="useSymbols" value="F"/>
			<param name="hideInvalid" value="F"/>
		</pagination>
		<!-- style settings: CSS class for links, filters, buttons and title -->
		<style link="reportLinks" filter="reportInputs" button="reportInputs" title="reportTitle" header="reportHeader" altstyle="reportCellA,reportCellB"/>
		<!-- columns configuration -->
		<columns sizes="35,25,14,14,12">
			<column name="name" alias="Name"/>
			<column name="manager" alias="Manager"/>
			<column name="start_date" alias="Start Date"/>
			<column name="end_date" alias="End Date"/>
			<column name="id_project" alias="Actions" sortable="F"/>
		</columns>
	</layout>
	<!-- datasource -->
	<datasource>
		<fields>
			pr.name,
			pp.name manager,
			pr.start_date,
			pr.end_date,
			pr.id_project
		</fields>
		<tables>
			projects pr inner join
			people pp on pr.id_manager = pp.id_people
		</tables>
		<clause/>
		<groupby/>
		<orderby>pr.name</orderby>
	</datasource>
</report>

=== marcospont/php2go/tags/RELEASE_0_5_7/examples/crud/list.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : list.xml, used by crud example -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_reports.dtd">
<report title="People List" baseuri="~PHP_SELF~?action=list">
	<!-- layout settings -->
	<layout grid="T" emptytemplate="F">
		<!-- pagination settings: style, style parameters -->
		<pagination style="REPORT_FIRSTPREVNEXTLAST">
			<param name="useButtons" value="T"/>
			<param name="useSymbols" value="F"/>
		</pagination>
		<!-- style settings: CSS class for links, filters, buttons and title -->
		<style link="reportLinks" filter="reportInputs" button="reportButtons" title="reportTitle" altstyle="reportCellA,reportCellB" header="reportHeader"/>
		<!-- columns configuration -->
		<columns sizes="35,10,10,35,10">
			<column name="name" alias="Name"/>
			<column name="sex" alias="Sex"/>
			<column name="active" alias="Active"/>
			<column name="country" alias="Country"/>
			<column name="id_people" alias="Actions" sortable="F"/>
		</columns>
	</layout>
	<!-- datasource -->
	<datasource>
		<fields>
			p.name,
			if(p.sex='M', 'Male', 'Female') sex,
			if(p.active=1, 'Yes', 'No') active,
			c.name country,
			p.id_people
		</fields>
		<tables>
			people p inner join
			country c on p.id_country = c.id_country</tables>
		<clause/>
		<groupby/>
		<orderby>p.name</orderby>
	</datasource>
</report>

=== marcospont/php2go/trunk/examples/reports.example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE report SYSTEM "..\docs\dtd\php2go_reports.dtd">
<report>
	<datasource>
		<fields>CLIENT.NAME as 'Name', CLIENT.ADDRESS as 'Address', CLIENT.PHONE as 'Phone', CITY.NAME as 'City'</fields>
		<tables>CLIENT inner join CITY on CLIENT.CITY_ID = CITY.CITY_ID</tables>
		<clause>CLIENT.STATUS = 1 and CLIENT.TYPE in (1,2,3)</clause>
		<groupby/>
		<orderby>CLIENT.NAME</orderby>
	</datasource>
	<datafilters>
		<datafilter label="Client Name" field="CLIENT.NAME" mask="string" index="0"/>
		<datafilter label="Client Address" field="CLIENT.ADDRESS" mask="string" index="1"/>
		<datafilter label="Client Birthday" field="CLIENT.BIRTHDATE" mask="date"/>
		<datafilter label="Client Status" field="CLIENT.STATUS" mask="integer"/>
		<datafilter label="Client City" field="CITY.NAME" mask="string" index="3"/>
	</datafilters>
</report>
