=== marcospont/php2go/docs/dtd/php2go_forms.dtd
<!-- This file is the document type specification for the PHP2Go forms API. -->
<!-- $Id$ -->
<!ENTITY % boolean "( T | F )">
<!ENTITY % color "CDATA">
<!ENTITY % identifier "NMTOKEN">
<!ENTITY % word "NMTOKEN">
<!ENTITY % number "CDATA">
<!ENTITY % text "CDATA">
<!ENTITY % weekdays "( 0 | 1 | 2 | 3 | 4 | 5 | 6 )">
<!ENTITY % align "( LEFT | CENTER | RIGHT )">
<!ENTITY % mask "( DIGIT | INTEGER | FLOAT | CURRENCY | CPFCNPJ | DATE | TIME | URL | EMAIL | WORD | ZIP )">
<!ENTITY % method "( GET | POST )">
<!ENTITY % type.btn "( SUBMIT | RESET | BUTTON | CLEAR | BACK )">
<!ENTITY % type.list "( JS | JSRS | AJAX )">
<!ENTITY % type.rul "( REGEX | EQ | NEQ | GT | LT | GOET | LOET | REQIF | REQIFEQ | REQIFNEQ | REQIFGT | REQIFLT | REQIFGOET | REQIFLOET )">
<!ENTITY % type.compare "( STRING | INTEGER | FLOAT | DATE )">
<!ENTITY % type.srch "( STRING | INTEGER | FLOAT | DATE | DATETIME )">
<!ENTITY % type.op "( EQ | NEQ | GT | LT | GOET | LOET | STARTING | ENDING | CONTAINING | IN | NOTIN | BETWEEN )">
<!ENTITY % type.image "( IMAGETYPE_PNG | IMAGETYPE_GIF | IMAGETYPE_JPEG | IMAGETYPE_XBM | IMAGETYPE_WBMP | IMAGETYPE_GD | IMAGETYPE_GD2 )">
<!ENTITY % regattrs
"	id %identifier; #IMPLIED
	name %identifier; #IMPLIED"
>
<!ENTITY % baseattrs
"	%regattrs;
	label %text; #IMPLIED
	help %text; #IMPLIED
	required %boolean; 'F'
	disabled %boolean; 'F'"
>
<!ENTITY % htmlattrs
"	style %text; #IMPLIED
	tabindex %number; #IMPLIED
	accesskey %text; #IMPLIED"
>
<!ENTITY % coreattrs
"	%baseattrs;
	%htmlattrs;"
>
<!ENTITY % editattrs
"	upper %boolean; 'F'
	lower %boolean; 'F'
	capitalize %boolean; 'F'
	autotrim %boolean; 'F'"
>
<!ENTITY % textattrs
"	maxlength %number; #IMPLIED
	minlength %number; #IMPLIED
	readonly %boolean; 'F'
	autocomplete %boolean; 'F'"
>
<!ENTITY % lengthattrs
"	size %number; #IMPLIED
	length %number; #IMPLIED"
>
<!ENTITY % sizeattrs
"	width %number; #IMPLIED
	height %number; #IMPLIED"
>
<!ENTITY % valueattrs
"	value %text; #IMPLIED
	default %text; #IMPLIED"
>
<!ENTITY % comboattrs
"	first %text; #IMPLIED
	nofirst %boolean; 'F'
	width %number; #IMPLIED
	multiple %boolean; 'F'
	size %number; #IMPLIED"
>
<!ENTITY % groupattrs
"	default %text; #IMPLIED
	cols %number; '1'
	tablewidth %number; #IMPLIED"
>
<!ENTITY % fld.basic
	"checkfield | checkgroup | combofield | dbcheckgroup | dbradiofield |
	editfield | filefield | hiddenfield | lookupfield | memofield |
	passwdfield | radiofield | textfield">
<!ENTITY % fld.special
	"autocompletefield | captchafield | colorpickerfield | datagrid | datepickerfield | editorfield |
	editsearchfield | editselectionfield | lookupchoicefield | lookupselectionfield |
	multicolumnlookupfield | rangefield">
<!ENTITY % fld.range
	"combofield | datepickerfield | editfield | lookupfield"
>
<!ENTITY % fld "%fld.basic; | %fld.special;">
<!ENTITY % fld.cond "%fld; | buttons | button | condsection">
<!ENTITY % rul.list "listener* | rule*">
<!ENTITY % rul.list.srch "listener* | rule* | search?">
<!ENTITY % rul.list.srch.opt "option+ | listener* | rule* | search?">
<!ENTITY % rul.list.srch.opto "option* | listener* | rule* | search?">
<!ENTITY % rul.list.srch.ds "datasource, ( listener* | rule* | search? )">
<!ENTITY % rul.list.srch.dso "datasource?, ( listener* | rule* | search? )">
<!ELEMENT form ( style? | errors? | help? | section+ | variable* )>
<!ATTLIST form
	method %method; #IMPLIED
	action %text; #IMPLIED
	target %identifier; #IMPLIED
	backurl %text; #IMPLIED
	accesskeyhighlight %boolean; #IMPLIED
	validatefunc %text; #IMPLIED
>
<!ELEMENT style EMPTY>
<!ATTLIST style
	input %text; #IMPLIED
	label %text; #IMPLIED
	button %text; #IMPLIED
	fieldset %text; #IMPLIED
	sectiontitle %text; #IMPLIED
	width %number; #IMPLIED
	align %align; #IMPLIED
	tablepadding %number; #IMPLIED
	tablespacing %number; #IMPLIED
	labelwidth %number; #IMPLIED
	labelalign %align; #IMPLIED
>
<!ELEMENT errors EMPTY>
<!ATTLIST errors
	style %text; #IMPLIED
	clientmode %identifier; #IMPLIED
	clientcontainer %identifier; #IMPLIED
	tplplaceholder %identifier; #IMPLIED
	showall %boolean; "T"
	headertext %text; #IMPLIED
	headerstyle %text; #IMPLIED
	listmode %identifier; #IMPLIED
>
<!ELEMENT help EMPTY>
<!ATTLIST help
	mode %identifier; #IMPLIED
	options %text; #IMPLIED
>
<!ELEMENT section ( %fld.cond; )*>
<!ATTLIST section
	id %identifier; #REQUIRED
	name %text; #REQUIRED
	condition %boolean; "F"
	evalfunction %text; #IMPLIED
	required_flag %boolean; "T"
	required_color %color; "#ff0000"
	required_text %text; "*"
>
<!ELEMENT condsection ( %fld.cond; )*>
<!ATTLIST condsection
	id %identifier; #REQUIRED
	evalfunction %text; #IMPLIED
	required_flag %boolean; #IMPLIED
	required_color %color; #IMPLIED
	required_text %text; #IMPLIED
>
<!ELEMENT autocompletefield ( ( choice+ | datasource? ), ( listener* | rule* | search? ) )>
<!ATTLIST autocompletefield
	%coreattrs;
	%valueattrs;
	%lengthattrs;
	%textattrs;
	lower %boolean; #IMPLIED
	upper %boolean; #IMPLIED
	source ( LOCAL | AJAX ) #IMPLIED
	multiple %boolean; #IMPLIED
	separator %boolean; #IMPLIED
	height %number; #IMPLIED
	maxchoices %number; #IMPLIED
	minchars %number; #IMPLIED
	ignorecase %boolean; #IMPLIED
	fullsearch %boolean; #IMPLIED
	autoselect %boolean; #IMPLIED
	choicevaluenode %identifier; #IMPLIED
	normalstyle %text; #IMPLIED
	hoverstyle %text; #IMPLIED
	selectedstyle %text; #IMPLIED
	ajaxoptions %text; #IMPLIED
	ajaxfield %text; #IMPLIED
	ajaxthrobber %text; #IMPLIED
>
<!ELEMENT captchafield ( %rul.list; )>
<!ATTLIST captchafield
	%coreattrs;
	%textattrs;
	%sizeattrs;
	noiselevel %number; "15"
	fontsize %number; "15"
	fontshadow %number; "3"
	fontangle %number; "30"
	imagepath %text; #IMPLIED
	imagetype %type.image; "IMAGETYPE_PNG"
>
<!ELEMENT checkfield ( %rul.list.srch; )>
<!ATTLIST checkfield
	%coreattrs;
	default %text; #IMPLIED
	caption %text; #IMPLIED
>
<!ELEMENT checkgroup ( %rul.list.srch.opt; )>
<!ATTLIST checkgroup
	%coreattrs;
	%groupattrs;
	shortcuts %boolean; #IMPLIED
>
<!ELEMENT colorpickerfield ( %rul.list.srch; )>
<!ATTLIST colorpickerfield
	%coreattrs;
	%valueattrs;
	mode ( FLAT | POPUP ) #IMPLIED
>
<!ELEMENT combofield ( %rul.list.srch.opto; )>
<!ATTLIST combofield
	%coreattrs;
	%comboattrs;
	default %text; #IMPLIED
>
<!ELEMENT datagrid ( fieldset, datasource )>
<!ATTLIST datagrid
	%baseattrs;
	showheader %boolean; "T"
	headers %text; #IMPLIED
	headerstyle %text; #IMPLIED
	cellstyle %text; #IMPLIED
	cellsizes %text; #IMPLIED
	tablewidth %number; #IMPLIED
	showcheckboxes %boolean; "F"
	emptygridmessage %text; #IMPLIED
>
<!ELEMENT datepickerfield ( %rul.list.srch; )>
<!ATTLIST datepickerfield
	%baseattrs;
	%valueattrs;
	style %text; #IMPLIED
	multiple %boolean; "F"
	datestatusfunc %text; #IMPLIED
	time %boolean; "F"
	firstweekday %weekdays; "0"
	yearrange %text; #IMPLIED
	showothers %boolean; "F"
	showweeknumbers %boolean; "F"
>
<!ELEMENT dbradiofield ( %rul.list.srch.ds; )>
<!ATTLIST dbradiofield
	%coreattrs;
	%groupattrs;
>
<!ELEMENT dbcheckgroup ( %rul.list.srch.ds; )>
<!ATTLIST dbcheckgroup
	%coreattrs;
	%groupattrs;
	shortcuts %boolean; #IMPLIED
>
<!ELEMENT editfield ( %rul.list.srch; )>
<!ATTLIST editfield
	%coreattrs;
	%valueattrs;
	%lengthattrs;
	%textattrs;
	align %align; #IMPLIED
	mask %mask; #IMPLIED
	calculator %boolean; "F"
	%editattrs;
>
<!ELEMENT editorfield EMPTY>
<!ATTLIST editorfield
	%baseattrs;
	%valueattrs;
	%sizeattrs;
	style %text; #IMPLIED
	stylesheet %text; #IMPLIED
	readonly %boolean; "F"
	resizemode ( HORIZONTAL | VERTICAL | BOTH | NONE ) "NONE"
>
<!ELEMENT editsearchfield ( datasource, datafilter+, lookupfield )>
<!ATTLIST editsearchfield
	%coreattrs;
	%lengthattrs;
	autodispatch %boolean; "F"
	autotrim %boolean; "F"
	btnimg %text; #IMPLIED
	btnvalue %text; #IMPLIED
	debug %boolean; "F"
	url %text; #IMPLIED
>
<!ELEMENT editselectionfield ( editfield, lookupfield, listener+ )>
<!ATTLIST editselectionfield
	%baseattrs;
	insfield %identifier; #IMPLIED
	remfield %identifier; #IMPLIED
	addimg %text; #IMPLIED
	remimg %text; #IMPLIED
	remallimg %text; #IMPLIED
	tablewidth %number; #IMPLIED
>
<!ELEMENT filefield ( %rul.list; )>
<!ATTLIST filefield
	%coreattrs;
	%lengthattrs;
	maxfilesize %text; #IMPLIED
	allowedtypes %text; #IMPLIED
	savefunction %text; #IMPLIED
	savepath %text; #IMPLIED
	savename %text; #IMPLIED
	savemode %text; "0644"
	overwrite %boolean; "F"
	uploadonvalidate %boolean; "T"
>
<!ELEMENT hiddenfield ( search? )>
<!ATTLIST hiddenfield
	%regattrs;
	%valueattrs;
>
<!ELEMENT lookupchoicefield ( %rul.list.srch.ds; )>
<!ATTLIST lookupchoicefield
	%coreattrs;
	%comboattrs;
	default %text; #IMPLIED
>
<!ELEMENT lookupfield ( %rul.list.srch.dso; )>
<!ATTLIST lookupfield
	%coreattrs;
	%comboattrs;
	default %text; #IMPLIED
>
<!ELEMENT lookupselectionfield ( lookupfield, lookupfield, listener+ )>
<!ATTLIST lookupselectionfield
	%coreattrs;
	insfield %identifier; #IMPLIED
	remfield %identifier; #IMPLIED
	addimg %text; #IMPLIED
	addallimg %text; #IMPLIED
	remimg %text; #IMPLIED
	remallimg %text; #IMPLIED
	tablewidth %number; #IMPLIED
>
<!ELEMENT multicolumnlookupfield ( %rul.list.srch.ds; )>
<!ATTLIST multicolumnlookupfield
	%coreattrs;
	headers %text; #IMPLIED
	width %number; #IMPLIED
	tablewidth %number; #IMPLIED
	tableheight %number; #IMPLIED
	tablestyle %text; #IMPLIED
	normalrowstyle %text; "mclookupNormal"
	selectedrowstyle %text; "mclookupSelected"
	hoverrowstyle %text; "mclookupHover"
>
<!ELEMENT memofield ( %rul.list.srch; )>
<!ATTLIST memofield
	%coreattrs;
	%valueattrs;
	%textattrs;
	cols %number; "40"
	rows %number; "5"
	charcount %boolean; "F"
	upper %boolean; "F"
	lower %boolean; "F"
>
<!ELEMENT passwdfield ( %rul.list.srch; )>
<!ATTLIST passwdfield
	%coreattrs;
	%valueattrs;
	%lengthattrs;
	%textattrs;
	align %align; #IMPLIED
	upper %boolean; "F"
	lower %boolean; "F"
>
<!ELEMENT radiofield ( %rul.list.srch.opt; )>
<!ATTLIST radiofield
	%coreattrs;
	%groupattrs;
>
<!ELEMENT rangefield ( ( %fld.range; ), ( %fld.range; ), search? )>
<!ATTLIST rangefield
	%coreattrs;
	readonly %boolean; "F"
	mask %mask; #IMPLIED
	startname %word; "start"
	endname %word; "end"
	surroundtext %text; #IMPLIED
	ruleequal %boolean; "F"
	rulemessage %text; #IMPLIED
>
<!ELEMENT textfield EMPTY>
<!ATTLIST textfield
	%regattrs;
	%valueattrs;
	label %text; #IMPLIED
	style %text; #IMPLIED
	help %text; #IMPLIED
>
<!ELEMENT buttons ( button+ )>
<!ELEMENT button ( listener* )>
<!ATTLIST button
	%regattrs;
	%htmlattrs;
	type %type.btn; #REQUIRED
	value %text; #IMPLIED
	alt %text; #IMPLIED
	disabled %boolean; "F"
	img %text; #IMPLIED
	swpimg %text; #IMPLIED
>
<!ELEMENT listener ( #PCDATA | param )*>
<!ATTLIST listener
	type %type.list; #REQUIRED
	event %text; #REQUIRED
	action %text; #IMPLIED
	autodispatchif %text; #IMPLIED
	file %text; #IMPLIED
	remote %word; #IMPLIED
	callback %word; #IMPLIED
	params %text; #IMPLIED
	debug %boolean; "F"
	url %text; #IMPLIED
	class %word; "AjaxRequest"
	formsubmit %boolean; "F"
>
<!ELEMENT rule ( #PCDATA )>
<!ATTLIST rule
	type %type.rul; #REQUIRED
	field %identifier; #IMPLIED
	value %text; #IMPLIED
	message %text; #IMPLIED
	comparetype %type.compare; #IMPLIED
>
<!ELEMENT search EMPTY>
<!ATTLIST search
	alias %text; #IMPLIED
	datatype %type.srch; #IMPLIED
	operator %type.op; #IMPLIED
	sqlfunc %text; #IMPLIED
	fieldfunc %text; #IMPLIED
	valuefunc %text; #IMPLIED
	descsource ( DISPLAY | VALUE ) "DISPLAY"
>
<!ELEMENT datafilter EMPTY>
<!ATTLIST datafilter
	id %identifier; #REQUIRED
	label %text; #REQUIRED
	expression %text; #REQUIRED
	mask %mask; #IMPLIED
>
<!ELEMENT datasource ( procedure | ( keyfield, displayfield?, lookuptable, clause?, groupby?, orderby?, limit?, groupfield?, groupdisplay? ) )>
<!ATTLIST datasource
	connection %identifier; #IMPLIED
>
<!ELEMENT keyfield ( #PCDATA )>
<!ELEMENT displayfield ( #PCDATA )>
<!ELEMENT lookuptable ( #PCDATA )>
<!ELEMENT clause ( #PCDATA )>
<!ELEMENT groupby ( #PCDATA )>
<!ELEMENT orderby ( #PCDATA )>
<!ELEMENT limit ( #PCDATA )>
<!ELEMENT groupfield ( #PCDATA )>
<!ELEMENT groupdisplay ( #PCDATA )>
<!ELEMENT procedure ( #PCDATA )>
<!ATTLIST procedure
	cursorname %word; #IMPLIED
>
<!ELEMENT option ( listener* )>
<!ATTLIST option
	value %text; #REQUIRED
	caption %text; #IMPLIED
	alt %text; #IMPLIED
	accesskey %text; #IMPLIED
	disabled %boolean; "F"
>
<!ELEMENT fieldset ( %fld.basic; )>
<!ELEMENT variable EMPTY>
<!ATTLIST variable
	name %identifier; #REQUIRED
	default %text; #IMPLIED
	searchorder %word; #IMPLIED
>
<!ELEMENT choice ( #PCDATA )>
<!ELEMENT param ( #PCDATA )>
<!ATTLIST param
	name %word; #REQUIRED
>

=== marcospont/php2go/examples/formcomponents/form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : form.xml, used by formcomponents example -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<variable name="subset" default="1"/>

	<section name="PHP2Go Form Components Part 1" id="section">

		<combofield name="subset" label="Choose the Subset" default="~subset~">
			<option value="1" caption="Subset 1"/>
			<option value="2" caption="Subset 2"/>
			<option value="3" caption="Subset 3"/>
			<listener type="JS" event="onChange" action="window.location.href='?subset='+this.value"/>
		</combofield>

		<!--
			the rangefield represents a pair of values of the same data type.
			php2go automatically adds a validation rule that expects that the second value
			is greater (or greater or equal) than the first

			- to create a rangefield, you must specify 2 "editfield" child nodes
			- the "mask" attribute in "rangefield" will overwrite any mask defitions on "editfield" nodes
		-->
		<rangefield
			name="date_range" label="RangeField" mask="DATE" required="T"
			startname="start" endname="end" surroundtext="Between %s and %s"
		>
			<editfield/>
			<editfield/>
		</rangefield>

		<!--
			the editsearch widget is a combo which is filled with the results of a simple search.
			the search is performed by a simple search widget, based on a set of search fields and a search term.
			the search request is made with the JSRS library, bundled with PHP2Go

			- to create an editsearchfield, you must specifiy one "lookupfield" child, the query "datasource" and at least one "datafilter" child
			- the "expression" attribute inside the "datafilter" node represents how the filter will be added in the SQL condition clause
		-->
		<editsearchfield
			name="edit_search" label="EditSearchField"
			required="T" autotrim="T" autodispatch="T" debug="F"
		>
			<datafilter id="1" label="Name" expression="code like '%%%s%%'" mask="STRING"/>
			<datafilter id="2" label="Date Added" expression="date_added > '%s'" mask="DATE"/>
			<datasource>
				<keyfield>id_product</keyfield>
				<displayfield>concat(code,' - ',short_desc)</displayfield>
				<lookuptable>products</lookuptable>
			</datasource>
			<lookupfield width="350"/>
		</editsearchfield>

		<!--
			the multicolumnlookupfield is a special lookupfield that displays the available
			options in an table. <keyfield> will be used as component's value, and all fields
			declared inside <displayfield> will be visible inside the option's table
		-->
		<multicolumnlookupfield
			name="multi_column" label="MultiColumnLookupField"
			required="T" width="300" tablewidth="400" tableheight="250"
			headers="Name,Address,Category"
		>
			<datasource>
				<keyfield>client_id</keyfield>
				<displayfield>name, address, category</displayfield>
				<lookuptable>client</lookuptable>
				<orderby>name</orderby>
			</datasource>
		</multicolumnlookupfield>

		<!--
			the lookupchoicefield component extends lookupfield's features by adding a text
			input above the select input which filters the list options. the filter is
			applied using the "starts with" rule
		-->
		<lookupchoicefield
			name="lookup_choice" label="LookupChoiceField"
			required="T" width="300" size="5"
		>
			<datasource>
				<keyfield>client_id</keyfield>
				<displayfield>name</displayfield>
				<lookuptable>client</lookuptable>
				<orderby>name</orderby>
			</datasource>
		</lookupchoicefield>

		<!--
			text input with security image.
			used to test tell computers from humans apart.
		-->
		<captchafield
			name="captcha" label="CaptchaField" required="T"
			size="10" length="6" width="160" height="50"
			noiselevel="20" fontsize="20" fontshadow="4"
			imagepath="../tmp/" imagetype="IMAGETYPE_PNG"
		/>

		<!-- button group -->
		<buttons>
			<button name="submit" type="SUBMIT" value="Submit"/>
			<!--
				some form components execute special routines when form.reset() is called.
				this button was inserted here so that you can check these behaviours
			-->
			<button name="reset" type="RESET" value="Reset"/>
			<!--
				demonstration of a button whose JS action is inside the node's CDATA-section
				in this case, the JS code toggles enable state of all form fields
			-->
			<button name="disable" type="BUTTON" value="Disable">
				<listener type="JS" event="onClick"><![CDATA[
					if (typeof window.lastOp == 'undefined') {
						window.lastOp = false;
					} else {
						window.lastOp = !window.lastOp;
					}
					if (window.lastOp === true) {
						Form.enableAll('form');
						this.value = "Disable";
					} else {
						Form.disableAll('form');
						this.value = "Enable";
					}
				]]></listener>
			</button>
			<!-- back button -->
			<button name="back" type="BACK" value="Back"/>
		</buttons>

	</section>

</form>

=== marcospont/php2go/branches/dev/examples/crudcomponents/form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : form.xml, used by crudcomponents example -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form method="POST" action="~REQUEST_URI~" backurl="~PHP_SELF~">
	<!-- variables -->
	<variable name="id_project" default="-1"/>
	<!-- layout & style settings -->
	<style input="input_style" label="label_style" button="button_style"/>
	<!-- error summary settings -->
	<errors
		style="error_style" listmode="FORM_ERROR_BULLET_LIST"
		headerstyle="error_header" clientmode="FORM_CLIENT_ERROR_DHTML"
		clientcontainer="error_container" tplplaceholder="error"
	/>
	<section id="project" name="Project Form">
		<!-- project data -->
		<editfield name="name" label="Name" size="60" length="40" required="T" tabindex="1"/>
		<editfield name="start_date" label="Start Date" size="10" length="12" mask="DATE" required="T" tabindex="2" default="TODAY"/>
		<editfield name="end_date" label="End Date" size="10" length="12" mask="DATE" required="T" tabindex="3">
			<rule type="GT" field="start_date"/>
		</editfield>
		<lookupfield name="id_manager" label="Manager" width="150" required="T" tabindex="4">
			<datasource>
				<keyfield>p.id_people</keyfield>
				<displayfield>p.name</displayfield>
				<lookuptable>people p</lookuptable>
				<orderby>p.name</orderby>
			</datasource>
		</lookupfield>
		<lookupselectionfield name="members" label="Members" required="T" insfield="added_members" remfield="removed_members">
			<lookupfield name="available" label="All People" width="150" size="5" tabindex="5">
				<datasource>
					<keyfield>id_people</keyfield>
					<displayfield>name</displayfield>
					<lookuptable>people</lookuptable>
					<orderby>name</orderby>
				</datasource>
			</lookupfield>
			<lookupfield name="selected" label="Selected" width="150" size="5" tabindex="6">
				<datasource>
					<keyfield>pp.id_people</keyfield>
					<displayfield>p.name</displayfield>
					<lookuptable>
						projects_people pp inner join
						people p on pp.id_people = p.id_people
					</lookuptable>
					<clause>pp.id_project = ~id_project~</clause>
					<orderby>p.name</orderby>
				</datasource>
			</lookupfield>
		</lookupselectionfield>
		<condsection id="details" evalfunction="evalCondSection">
			<!-- new task -->
			<editfield name="task_name" label="Name" size="10" length="20" tabindex="7"/>
			<editfield name="task_description" label="Description" size="25" length="200" tabindex="8"/>
			<lookupfield name="task_id_owner" label="Owner" nofirst="T" tabindex="9">
				<datasource>
					<keyfield>pp.id_people</keyfield>
					<displayfield>p.name</displayfield>
					<lookuptable>
						projects_people pp inner join
						people p on pp.id_people = p.id_people
					</lookuptable>
					<clause>pp.id_project = ~id_project~</clause>
					<orderby>p.name</orderby>
				</datasource>
			</lookupfield>
			<combofield name="task_status" label="Status" nofirst="T" tabindex="10">
				<option value="O" caption="O"/>
				<option value="A" caption="A"/>
				<option value="C" caption="C"/>
			</combofield>
			<combofield name="task_priority" label="Priority" nofirst="T" default="N" tabindex="11">
				<option value="L" caption="L"/>
				<option value="N" caption="N"/>
				<option value="H" caption="H"/>
			</combofield>
			<editfield name="task_start_date" label="Start Date" size="8" length="10" mask="DATE" tabindex="12" default="TODAY"/>
			<editfield name="task_end_date" label="End Date" size="8" length="10" mask="DATE" tabindex="13"/>
			<button name="add" value="Add" type="BUTTON" tabindex="14">
				<listener type="AJAX" event="onclick">
					<param name="method">POST</param>
					<param name="params">{action:"add_task", id_project:~id_project~}</param>
					<param name="form">project</param>
					<param name="onSuccess"><![CDATA[
						alert(response.responseText);
						window.location.href = window.location;
					]]></param>
					<param name="onFailure"><![CDATA[
						alert(response.responseText);
						$('task_name').focus();
					]]></param>
				</listener>
			</button>
			<!-- edit tasks -->
			<datagrid
				name="tasks" label="Tasks" tablewidth="750" style="dataGrid"
				headers="#,Name,Description,Owner,Status,Priority,Start Date,End Date"
				emptygridmessage="This project has no tasks" showcheckboxes="T" tabindex="15"
			>
				<datasource>
					<keyfield>id_task</keyfield>
					<displayfield>
						id_task, name, description, id_owner, status, priority,
						date_format(start_date, '%d/%m/%Y') start_date,
						date_format(end_date, '%d/%m/%Y') end_date
					</displayfield>
					<lookuptable>tasks</lookuptable>
					<clause>id_project = ~id_project~</clause>
					<orderby>name</orderby>
				</datasource>
				<fieldset>
					<editfield name="name" size="10" length="20" required="T"/>
					<editfield name="description" size="25" length="200" required="T"/>
					<lookupfield name="id_owner" nofirst="T" required="T">
						<datasource>
							<keyfield>pp.id_people</keyfield>
							<displayfield>p.name</displayfield>
							<lookuptable>
								projects_people pp inner join
								people p on pp.id_people = p.id_people
							</lookuptable>
							<clause>pp.id_project = ~id_project~</clause>
							<orderby>p.name</orderby>
						</datasource>
					</lookupfield>
					<combofield name="status">
						<option value="O" caption="O"/>
						<option value="A" caption="A"/>
						<option value="C" caption="C"/>
					</combofield>
					<combofield name="priority">
						<option value="L" caption="L"/>
						<option value="N" caption="N"/>
						<option value="H" caption="H"/>
					</combofield>
					<editfield name="start_date" label="Start Date" size="8" length="10" mask="DATE" required="T"/>
					<editfield name="end_date" label="End Date" size="8" length="10" mask="DATE" required="T"/>
				</fieldset>
			</datagrid>
		</condsection>
		<button name="send" value="Send" type="SUBMIT" tabindex="16"/>
		<button name="back" value="Back" type="BACK" tabindex="17"/>
		<button name="delete" value="Delete Tasks" type="BUTTON" tabindex="18">
			<listener type="AJAX" event="onclick">
				<param name="params">{action:"delete_tasks"}</param>
				<param name="form">project</param>
				<param name="formValidate">false</param>
				<param name="onSuccess"><![CDATA[
					alert(response.responseText);
					window.location.href = window.location;
				]]></param>
				<param name="onFailure"><![CDATA[
					alert(response.responseText);
				]]></param>
			</listener>
		</button>
	</section>
</form>

=== marcospont/php2go/examples/crud/form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : form.xml, used by crud example -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form method="POST" action="~REQUEST_URI~">
	<!-- layout & style settings -->
	<style
		input="input_style" label="label_style" button="button_style"
		fieldset="fieldset_style" sectiontitle="legend_style"
		width="715" labelwidth="0.15"
	/>
	<!-- error summary settings -->
	<errors
		style="error_style" listmode="FORM_ERROR_BULLET_LIST"
		headerstyle="error_header" clientmode="FORM_CLIENT_ERROR_DHTML"
	/>
	<section id="people" name="People Form">
		<editfield name="name" label="Name" size="30" length="50" required="T"/>
		<combofield name="sex" label="Sex" width="80" required="T">
			<option value="M" caption="Male"/>
			<option value="F" caption="Female"/>
		</combofield>
		<editfield name="birth_date" label="Birth Date" size="10" length="12" mask="DATE" required="T"/>
		<editfield name="address" label="Address" size="40" length="100" required="T"/>
		<lookupfield name="id_country" label="Country" width="200" required="T">
			<datasource>
				<keyfield>id_country</keyfield>
				<displayfield>name</displayfield>
				<lookuptable>country</lookuptable>
				<orderby>name</orderby>
			</datasource>
		</lookupfield>
		<memofield name="notes" label="Notes" rows="5" cols="50"/>
		<checkfield name="active" caption="Is active" default="T"/>
		<buttons>
			<button name="send" value="Send" type="SUBMIT"/>
			<button name="cancel" value="Cancel" type="BACK"/>
		</buttons>
	</section>
</form>

=== marcospont/php2go/tags/RELEASE_0_5_6/examples/resources/formcomponents3.example.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : formcomponents.example.xml, used at formcomponents.example.php -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<variable name="subset" default="1"/>

	<section name="PHP2Go Form Components Part 3" id="section">

		<combofield name="subset" label="Choose the Subset" default="~subset~">
			<option value="1" caption="Subset 1"/>
			<option value="2" caption="Subset 2"/>
			<option value="3" caption="Subset 3"/>
			<listener type="JS" event="onChange" action="window.location.href='?subset='+this.value"/>
		</combofield>

		<!--
			autocompletefield is a text input (or textarea, when using multiple selection)
			enhanced with autocomplete funcionality. Autocomplete choices can be stored locally
			(inside the JS component) or retrieved in runtime using Ajax calls. The component
			also supports customizing how search is made, layout settings and other parameters
		-->
		<autocompletefield
			name="auto_complete" label="AutoCompleteField"
			size="30" required="T" source="AJAX" multiple="F"
			ignorecase="T" fullsearch="T" height="80"
			minchars="1" maxchoices="10" autoselect="F"
		>
			<datasource>
				<keyfield>client_id</keyfield>
				<displayfield>name</displayfield>
				<lookuptable>client</lookuptable>
				<orderby>name</orderby>
			</datasource>
		</autocompletefield>

		<!--
			datepickerfield is a date selection tool (single or multiple) based
			on the bundled JSCalendar (http://www.dynarch.com/projects/calendar/)
		-->
		<datepickerfield
			name="date_picker" label="DatePickerField"
			multiple="T" yearrange="2002,2008" required="T"
		/>

		<!--
			colorpickerfield is a simple color selection tool. it's based on a palette
			of 228 colors; selected value is stored in RGB format
		-->
		<colorpickerfield
			name="color_picker" label="ColorPickerField" mode="POPUP" required="T"
		/>

		<!-- button group -->
		<buttons>
			<button name="submit" type="SUBMIT" value="Submit"/>
			<!--
				some form components execute special routines when form.reset() is called.
				this button was inserted here so that you can check these behaviours
			-->
			<button name="reset" type="RESET" value="Reset"/>
			<!--
				demonstration of a button whose JS action is inside the node's CDATA-section
				in this case, the JS code toggles enable state of all form fields
			-->
			<button name="disable" type="BUTTON" value="Disable">
				<listener type="JS" event="onClick"><![CDATA[
					if (typeof window.lastOp == 'undefined') {
						window.lastOp = false;
					} else {
						window.lastOp = !window.lastOp;
					}
					if (window.lastOp === true) {
						Form.enableAll('form');
						this.value = "Disable";
					} else {
						Form.disableAll('form');
						this.value = "Enable";
					}
				]]></listener>
			</button>
			<!-- back button -->
			<button name="back" type="BACK" value="Back"/>
		</buttons>

	</section>

</form>
