=== marcospont/php2go/docs/dtd/php2go_forms.dtd
<!-- This file is the document type specification for the PHP2Go forms API. -->
<!-- $Id$ -->
<!ENTITY % boolean "( T | F )">
<!ENTITY % color "CDATA">
<!ENTITY % identifier "NMTOKEN">
<!ENTITY % word "NMTOKEN">
<!ENTITY % number "CDATA">
<!ENTITY % text "CDATA">
<!ENTITY % weekdays "( 0 | 1 | 2 | 3 | 4 | 5 | 6 )">
<!ENTITY % align "( LEFT | CENTER | RIGHT )">
<!ENTITY % mask "( DIGIT | INTEGER | FLOAT | CURRENCY | CPFCNPJ | DATE | TIME | URL | EMAIL | WORD | ZIP )">
<!ENTITY % method "( GET | POST )">
<!ENTITY % type.btn "( SUBMIT | RESET | BUTTON | CLEAR | BACK )">
<!ENTITY % type.list "( JS | JSRS | AJAX )">
<!ENTITY % type.rul "( REGEX | EQ | NEQ | GT | LT | GOET | LOET | REQIF | REQIFEQ | REQIFNEQ | REQIFGT | REQIFLT | REQIFGOET | REQIFLOET )">
<!ENTITY % type.compare "( STRING | INTEGER | FLOAT | DATE )">
<!ENTITY % type.srch "( STRING | INTEGER | FLOAT | DATE | DATETIME )">
<!ENTITY % type.op "( EQ | NEQ | GT | LT | GOET | LOET | STARTING | ENDING | CONTAINING | IN | NOTIN | BETWEEN )">
<!ENTITY % type.image "( IMAGETYPE_PNG | IMAGETYPE_GIF | IMAGETYPE_JPEG | IMAGETYPE_XBM | IMAGETYPE_WBMP | IMAGETYPE_GD | IMAGETYPE_GD2 )">
<!ENTITY % regattrs
"	id %identifier; #IMPLIED
	name %identifier; #IMPLIED"
>
<!ENTITY % baseattrs
"	%regattrs;
	label %text; #IMPLIED
	help %text; #IMPLIED
	required %boolean; 'F'
	disabled %boolean; 'F'"
>
<!ENTITY % htmlattrs
"	style %text; #IMPLIED
	tabindex %number; #IMPLIED
	accesskey %text; #IMPLIED"
>
<!ENTITY % coreattrs
"	%baseattrs;
	%htmlattrs;"
>
<!ENTITY % editattrs
"	upper %boolean; 'F'
	lower %boolean; 'F'
	capitalize %boolean; 'F'
	autotrim %boolean; 'F'"
>
<!ENTITY % textattrs
"	maxlength %number; #IMPLIED
	minlength %number; #IMPLIED
	readonly %boolean; 'F'
	autocomplete %boolean; 'F'"
>
<!ENTITY % lengthattrs
"	size %number; #IMPLIED
	length %number; #IMPLIED"
>
<!ENTITY % sizeattrs
"	width %number; #IMPLIED
	height %number; #IMPLIED"
>
<!ENTITY % valueattrs
"	value %text; #IMPLIED
	default %text; #IMPLIED"
>
<!ENTITY % comboattrs
"	first %text; #IMPLIED
	nofirst %boolean; 'F'
	width %number; #IMPLIED
	multiple %boolean; 'F'
	size %number; #IMPLIED"
>
<!ENTITY % groupattrs
"	default %text; #IMPLIED
	cols %number; '1'
	tablewidth %number; #IMPLIED"
>
<!ENTITY % fld.basic
	"checkfield | checkgroup | combofield | dbcheckgroup | dbradiofield |
	editfield | filefield | hiddenfield | lookupfield | memofield |
	passwdfield | radiofield | textfield">
<!ENTITY % fld.special
	"autocompletefield | captchafield | colorpickerfield | datagrid | datepickerfield | editorfield |
	editsearchfield | editselectionfield | lookupchoicefield | lookupselectionfield |
	multicolumnlookupfield | rangefield">
<!ENTITY % fld.range
	"combofield | datepickerfield | editfield | lookupfield"
>
<!ENTITY % fld "%fld.basic; | %fld.special;">
<!ENTITY % fld.cond "%fld; | buttons | button | condsection">
<!ENTITY % rul.list "listener* | rule*">
<!ENTITY % rul.list.srch "listener* | rule* | search?">
<!ENTITY % rul.list.srch.opt "option+ | listener* | rule* | search?">
<!ENTITY % rul.list.srch.opto "option* | listener* | rule* | search?">
<!ENTITY % rul.list.srch.ds "datasource, ( listener* | rule* | search? )">
<!ENTITY % rul.list.srch.dso "datasource?, ( listener* | rule* | search? )">
<!ELEMENT form ( style? | errors? | help? | section+ | variable* )>
<!ATTLIST form
	method %method; #IMPLIED
	action %text; #IMPLIED
	target %identifier; #IMPLIED
	backurl %text; #IMPLIED
	accesskeyhighlight %boolean; #IMPLIED
	validatefunc %text; #IMPLIED
>
<!ELEMENT style EMPTY>
<!ATTLIST style
	input %text; #IMPLIED
	label %text; #IMPLIED
	button %text; #IMPLIED
	fieldset %text; #IMPLIED
	sectiontitle %text; #IMPLIED
	width %number; #IMPLIED
	align %align; #IMPLIED
	tablepadding %number; #IMPLIED
	tablespacing %number; #IMPLIED
	labelwidth %number; #IMPLIED
	labelalign %align; #IMPLIED
>
<!ELEMENT errors EMPTY>
<!ATTLIST errors
	style %text; #IMPLIED
	clientmode %identifier; #IMPLIED
	clientcontainer %identifier; #IMPLIED
	tplplaceholder %identifier; #IMPLIED
	showall %boolean; "T"
	headertext %text; #IMPLIED
	headerstyle %text; #IMPLIED
	listmode %identifier; #IMPLIED
>
<!ELEMENT help EMPTY>
<!ATTLIST help
	mode %identifier; #IMPLIED
	options %text; #IMPLIED
>
<!ELEMENT section ( %fld.cond; )*>
<!ATTLIST section
	id %identifier; #REQUIRED
	name %text; #REQUIRED
	condition %boolean; "F"
	evalfunction %text; #IMPLIED
	required_flag %boolean; "T"
	required_color %color; "#ff0000"
	required_text %text; "*"
>
<!ELEMENT condsection ( %fld.cond; )*>
<!ATTLIST condsection
	id %identifier; #REQUIRED
	evalfunction %text; #IMPLIED
	required_flag %boolean; #IMPLIED
	required_color %color; #IMPLIED
	required_text %text; #IMPLIED
>
<!ELEMENT autocompletefield ( ( choice+ | datasource? ), ( listener* | rule* | search? ) )>
<!ATTLIST autocompletefield
	%coreattrs;
	%valueattrs;
	%lengthattrs;
	%textattrs;
	lower %boolean; #IMPLIED
	upper %boolean; #IMPLIED
	source ( LOCAL | AJAX ) #IMPLIED
	multiple %boolean; #IMPLIED
	separator %boolean; #IMPLIED
	height %number; #IMPLIED
	maxchoices %number; #IMPLIED
	minchars %number; #IMPLIED
	ignorecase %boolean; #IMPLIED
	fullsearch %boolean; #IMPLIED
	autoselect %boolean; #IMPLIED
	choicevaluenode %identifier; #IMPLIED
	normalstyle %text; #IMPLIED
	hoverstyle %text; #IMPLIED
	selectedstyle %text; #IMPLIED
	ajaxoptions %text; #IMPLIED
	ajaxfield %text; #IMPLIED
	ajaxthrobber %text; #IMPLIED
>
<!ELEMENT captchafield ( %rul.list; )>
<!ATTLIST captchafield
	%coreattrs;
	%textattrs;
	%sizeattrs;
	noiselevel %number; "15"
	fontsize %number; "15"
	fontshadow %number; "3"
	fontangle %number; "30"
	imagepath %text; #IMPLIED
	imagetype %type.image; "IMAGETYPE_PNG"
>
<!ELEMENT checkfield ( %rul.list.srch; )>
<!ATTLIST checkfield
	%coreattrs;
	default %text; #IMPLIED
	caption %text; #IMPLIED
>
<!ELEMENT checkgroup ( %rul.list.srch.opt; )>
<!ATTLIST checkgroup
	%coreattrs;
	%groupattrs;
	shortcuts %boolean; #IMPLIED
>
<!ELEMENT colorpickerfield ( %rul.list.srch; )>
<!ATTLIST colorpickerfield
	%coreattrs;
	%valueattrs;
	mode ( FLAT | POPUP ) #IMPLIED
>
<!ELEMENT combofield ( %rul.list.srch.opto; )>
<!ATTLIST combofield
	%coreattrs;
	%comboattrs;
	default %text; #IMPLIED
>
<!ELEMENT datagrid ( fieldset, datasource )>
<!ATTLIST datagrid
	%baseattrs;
	showheader %boolean; "T"
	headers %text; #IMPLIED
	headerstyle %text; #IMPLIED
	cellstyle %text; #IMPLIED
	cellsizes %text; #IMPLIED
	tablewidth %number; #IMPLIED
	showcheckboxes %boolean; "F"
	emptygridmessage %text; #IMPLIED
>
<!ELEMENT datepickerfield ( %rul.list.srch; )>
<!ATTLIST datepickerfield
	%baseattrs;
	%valueattrs;
	style %text; #IMPLIED
	multiple %boolean; "F"
	datestatusfunc %text; #IMPLIED
	time %boolean; "F"
	firstweekday %weekdays; "0"
	yearrange %text; #IMPLIED
	showothers %boolean; "F"
	showweeknumbers %boolean; "F"
>
<!ELEMENT dbradiofield ( %rul.list.srch.ds; )>
<!ATTLIST dbradiofield
	%coreattrs;
	%groupattrs;
>
<!ELEMENT dbcheckgroup ( %rul.list.srch.ds; )>
<!ATTLIST dbcheckgroup
	%coreattrs;
	%groupattrs;
	shortcuts %boolean; #IMPLIED
>
<!ELEMENT editfield ( %rul.list.srch; )>
<!ATTLIST editfield
	%coreattrs;
	%valueattrs;
	%lengthattrs;
	%textattrs;
	align %align; #IMPLIED
	mask %mask; #IMPLIED
	calculator %boolean; "F"
	%editattrs;
>
<!ELEMENT editorfield EMPTY>
<!ATTLIST editorfield
	%baseattrs;
	%valueattrs;
	%sizeattrs;
	style %text; #IMPLIED
	stylesheet %text; #IMPLIED
	readonly %boolean; "F"
	resizemode ( HORIZONTAL | VERTICAL | BOTH | NONE ) "NONE"
>
<!ELEMENT editsearchfield ( datasource, datafilter+, lookupfield )>
<!ATTLIST editsearchfield
	%coreattrs;
	%lengthattrs;
	autodispatch %boolean; "F"
	autotrim %boolean; "F"
	btnimg %text; #IMPLIED
	btnvalue %text; #IMPLIED
	debug %boolean; "F"
	url %text; #IMPLIED
>
<!ELEMENT editselectionfield ( editfield, lookupfield, listener+ )>
<!ATTLIST editselectionfield
	%baseattrs;
	insfield %identifier; #IMPLIED
	remfield %identifier; #IMPLIED
	addimg %text; #IMPLIED
	remimg %text; #IMPLIED
	remallimg %text; #IMPLIED
	tablewidth %number; #IMPLIED
>
<!ELEMENT filefield ( %rul.list; )>
<!ATTLIST filefield
	%coreattrs;
	%lengthattrs;
	maxfilesize %text; #IMPLIED
	allowedtypes %text; #IMPLIED
	savefunction %text; #IMPLIED
	savepath %text; #IMPLIED
	savename %text; #IMPLIED
	savemode %text; "0644"
	overwrite %boolean; "F"
	uploadonvalidate %boolean; "T"
>
<!ELEMENT hiddenfield ( search? )>
<!ATTLIST hiddenfield
	%regattrs;
	%valueattrs;
>
<!ELEMENT lookupchoicefield ( %rul.list.srch.ds; )>
<!ATTLIST lookupchoicefield
	%coreattrs;
	%comboattrs;
	default %text; #IMPLIED
>
<!ELEMENT lookupfield ( %rul.list.srch.dso; )>
<!ATTLIST lookupfield
	%coreattrs;
	%comboattrs;
	default %text; #IMPLIED
>
<!ELEMENT lookupselectionfield ( lookupfield, lookupfield, listener+ )>
<!ATTLIST lookupselectionfield
	%coreattrs;
	insfield %identifier; #IMPLIED
	remfield %identifier; #IMPLIED
	addimg %text; #IMPLIED
	addallimg %text; #IMPLIED
	remimg %text; #IMPLIED
	remallimg %text; #IMPLIED
	tablewidth %number; #IMPLIED
>
<!ELEMENT multicolumnlookupfield ( %rul.list.srch.ds; )>
<!ATTLIST multicolumnlookupfield
	%coreattrs;
	headers %text; #IMPLIED
	width %number; #IMPLIED
	tablewidth %number; #IMPLIED
	tableheight %number; #IMPLIED
	tablestyle %text; #IMPLIED
	normalrowstyle %text; "mclookupNormal"
	selectedrowstyle %text; "mclookupSelected"
	hoverrowstyle %text; "mclookupHover"
>
<!ELEMENT memofield ( %rul.list.srch; )>
<!ATTLIST memofield
	%coreattrs;
	%valueattrs;
	%textattrs;
	cols %number; "40"
	rows %number; "5"
	charcount %boolean; "F"
	upper %boolean; "F"
	lower %boolean; "F"
>
<!ELEMENT passwdfield ( %rul.list.srch; )>
<!ATTLIST passwdfield
	%coreattrs;
	%valueattrs;
	%lengthattrs;
	%textattrs;
	align %align; #IMPLIED
	upper %boolean; "F"
	lower %boolean; "F"
>
<!ELEMENT radiofield ( %rul.list.srch.opt; )>
<!ATTLIST radiofield
	%coreattrs;
	%groupattrs;
>
<!ELEMENT rangefield ( ( %fld.range; ), ( %fld.range; ), search? )>
<!ATTLIST rangefield
	%coreattrs;
	readonly %boolean; "F"
	mask %mask; #IMPLIED
	startname %word; "start"
	endname %word; "end"
	surroundtext %text; #IMPLIED
	ruleequal %boolean; "F"
	rulemessage %text; #IMPLIED
>
<!ELEMENT textfield EMPTY>
<!ATTLIST textfield
	%regattrs;
	%valueattrs;
	label %text; #IMPLIED
	style %text; #IMPLIED
	help %text; #IMPLIED
>
<!ELEMENT buttons ( button+ )>
<!ELEMENT button ( listener* )>
<!ATTLIST button
	%regattrs;
	%htmlattrs;
	type %type.btn; #REQUIRED
	value %text; #IMPLIED
	alt %text; #IMPLIED
	disabled %boolean; "F"
	img %text; #IMPLIED
	swpimg %text; #IMPLIED
>
<!ELEMENT listener ( #PCDATA | param )*>
<!ATTLIST listener
	type %type.list; #REQUIRED
	event %text; #REQUIRED
	action %text; #IMPLIED
	autodispatchif %text; #IMPLIED
	file %text; #IMPLIED
	remote %word; #IMPLIED
	callback %word; #IMPLIED
	params %text; #IMPLIED
	debug %boolean; "F"
	url %text; #IMPLIED
	class %word; "AjaxRequest"
	formsubmit %boolean; "F"
>
<!ELEMENT rule ( #PCDATA )>
<!ATTLIST rule
	type %type.rul; #REQUIRED
	field %identifier; #IMPLIED
	value %text; #IMPLIED
	message %text; #IMPLIED
	comparetype %type.compare; #IMPLIED
>
<!ELEMENT search EMPTY>
<!ATTLIST search
	alias %text; #IMPLIED
	datatype %type.srch; #IMPLIED
	operator %type.op; #IMPLIED
	sqlfunc %text; #IMPLIED
	fieldfunc %text; #IMPLIED
	valuefunc %text; #IMPLIED
	descsource ( DISPLAY | VALUE ) "DISPLAY"
>
<!ELEMENT datafilter EMPTY>
<!ATTLIST datafilter
	id %identifier; #REQUIRED
	label %text; #REQUIRED
	expression %text; #REQUIRED
	mask %mask; #IMPLIED
>
<!ELEMENT datasource ( procedure | ( keyfield, displayfield?, lookuptable, clause?, groupby?, orderby?, limit?, groupfield?, groupdisplay? ) )>
<!ATTLIST datasource
	connection %identifier; #IMPLIED
>
<!ELEMENT keyfield ( #PCDATA )>
<!ELEMENT displayfield ( #PCDATA )>
<!ELEMENT lookuptable ( #PCDATA )>
<!ELEMENT clause ( #PCDATA )>
<!ELEMENT groupby ( #PCDATA )>
<!ELEMENT orderby ( #PCDATA )>
<!ELEMENT limit ( #PCDATA )>
<!ELEMENT groupfield ( #PCDATA )>
<!ELEMENT groupdisplay ( #PCDATA )>
<!ELEMENT procedure ( #PCDATA )>
<!ATTLIST procedure
	cursorname %word; #IMPLIED
>
<!ELEMENT option ( listener* )>
<!ATTLIST option
	value %text; #REQUIRED
	caption %text; #IMPLIED
	alt %text; #IMPLIED
	accesskey %text; #IMPLIED
	disabled %boolean; "F"
>
<!ELEMENT fieldset ( %fld.basic; )>
<!ELEMENT variable EMPTY>
<!ATTLIST variable
	name %identifier; #REQUIRED
	default %text; #IMPLIED
	searchorder %word; #IMPLIED
>
<!ELEMENT choice ( #PCDATA )>
<!ELEMENT param ( #PCDATA )>
<!ATTLIST param
	name %word; #REQUIRED
>

=== marcospont/php2go/examples/searchform/form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : searchform.example.xml, used at searchform.example.php -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>
	<section name="PHP2Go Search Form Example" id="section">
		<editfield name="code" label="Code" upper="T" autotrim="T">
			<search alias="p.code" operator="EQ"/>
		</editfield>
		<editfield name="short_desc" label="Short Description">
			<search alias="p.short_desc" fieldfunc="trim(%s)" valuefunc="trim"/>
		</editfield>
		<combofield name="category" label="Category" multiple="T" size="2">
			<option value="1" caption="Books"/>
			<option value="2" caption="DVD"/>
			<search alias="p.id_category" datatype="INTEGER"/>
		</combofield>
		<rangefield name="added" label="Date Added" surroundtext="From %s to %s" ruleequal="T" mask="DATE">
			<editfield/>
			<editfield/>
			<search alias="p.date_added"/>
		</rangefield>
		<rangefield name="price" label="Price" surroundtext="Between %s and %s">
			<editfield mask="FLOAT-10:2"/>
			<editfield mask="FLOAT-10:2"/>
			<search alias="p.price"/>
		</rangefield>
		<combofield name="amount" label="Available Amount">
			<option value="10" caption="More than 10"/>
			<option value="50" caption="More than 50"/>
			<option value="100" caption="More than 100"/>
			<search alias="p.amount" operator="GOET" datatype="INTEGER" descsource="VALUE"/>
		</combofield>
		<checkfield name="active" caption="Active" default="T">
			<search alias="p.active"/>
		</checkfield>
		<buttons>
			<button name="submit" type="SUBMIT" value="Submit"/>
			<button name="reset" type="RESET" value="Reset"/>
		</buttons>
	</section>
</form>

=== marcospont/php2go/examples/formservervalidation/form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form method="POST" action="~REQUEST_URI~">
	<!-- CSS classes for inputs and labels; form width and label align (FormBasic only) -->
	<style input="input_style" label="label_style" fieldset="fieldset_style" sectiontitle="legend_style" width="800" labelwidth="0.15"/>
	<!--
		CSS class for errors, header text and header style for the error summary;
		Display options (client/server) for error summary
	-->
	<errors
		style="error_style" listmode="FORM_ERROR_BULLET_LIST"
		headertext="" headerstyle="error_header" tplplaceholder="error"
		clientmode="FORM_CLIENT_ERROR_DHTML" clientcontainer="form_client_errors"
	/>
	<section id="section" name="Form validated on server">
		<!-- an EDITFIELD using DATE mask and containing 2 rules to validate the input value -->
		<editfield name="Edit1" label="Date" size="12" length="10" mask="DATE" required="T">
			<!--
				comparison rule, using GOET operator (greater or equal than)
				the comparison value (VALUE attribute) used variable substitution (~var~) and PHP code (#php_code#)
			-->
			<rule type="GOET" value="01/01/~#date('Y')#~" message="Date must be greater or equal than first day of current year"/>
			<!--
				comparision rule, using LOET operator (less or equal than)
			-->
			<rule type="LOET" value="TODAY-3M"/>
		</editfield>
		<!-- an EDITFIELD (TEXT input) containing a REGEX rule (test the field value against a pattern) -->
		<editfield name="Edit2" label="Edit" size="20" required="T" autotrim="T" upper="T">
			<rule type="REGEX" value="^[0-9]{3}\-[a-zA-Z]{5}$"/>
		</editfield>
		<combofield name="Combo1" label="Combo 1" multiple="T" size="5" width="180" required="T">
			<option value="1" caption="Angelina Jolie"/>
			<option value="2" caption="Salma Hayek"/>
			<option value="3" caption="Denise Richards"/>
			<option value="4" caption="Paris Hilton"/>
			<option value="5" caption="Alicia Silverstone"/>
			<option value="6" caption="Christina Aguilera"/>
			<option value="7" caption="Beyoncé Knowles"/>
			<option value="8" caption="Katie Holmes"/>
			<option value="9" caption="Britney Spears"/>
			<option value="10" caption="Jennifer Love Hewitt"/>
		</combofield>
		<!--
			a FILEFIELD with file upload configuration settings
			if you use server validation (Form::isPosted and Form::isValid), the upload operation
			will be done automatically, unless you set UPLOADONVALIDATE to "F"
		-->
		<filefield name="File1" label="File 1" size="20" uploadonvalidate="T" maxfilesize="100K" allowedtypes="image/jpeg,image/pjpeg,image/gif,image/png" savefunction="uploadHandler" savemode="0777" savepath="../tmp/"/>
		<!--
			a simple SUBMIT button
			switch the two lines to see the default HTML button or the image button
		-->
		<!--<button name="send" value="Send" type="submit"/>-->
		<button name="send" img="../common/send.gif" type="SUBMIT"/>
	</section>
</form>

=== marcospont/php2go/tags/RELEASE_0_5_7/examples/formtemplate/form.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- PHP2Go Examples : form.xml, used by formtemplate example -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<!-- a "section" is a set of fields; you can flag it as conditional, then its visibility will be defined by a user function or method -->
	<!-- the section name will appear in the template if a variable {section_[section_id]} is declared -->
	<section name="PHP2Go Form Example" id="section" required_flag="T" required_color="#0000ff" required_text=" (*)">

		<!-- the editfield implements an HTML input of type "TEXT" -->
		<editfield name="edit_field" label="Date" mask="DATE" size="12" length="10" required="T" help="This fields requires a date greater than the first day of the current month, and less than today plus 2 days" accesskey="D">
			<!-- a rule using PHP code (pattern ~#code#~), validating if the provided date is "greater than" (GT) the first day of the current month -->
			<rule type="GT" value="01/~#date('m/Y')#~"/>
			<!-- the text fields that use the mask "DATE" accept date expressions in the "VALUE" attribute of the rules -->
			<rule type="LT" value="TODAY+2Y"/>
		</editfield>

		<!-- the passwdfield implements an HTML input of type "PASSWORD" -->
		<passwdfield name="passwd_field" label="Password" value="xxxxxx" help="This is a sample of a simple password field" accesskey="P"/>

		<!-- the rangefield is a composite field containing two editfield child nodes -->
		<!-- the interval is posted as an array, and the keys are defined by the attributes startname and endname -->
		<!-- a comparison rule is added automatically. using the attribute ruleequal, you can define if the interval accepts equal values -->
		<rangefield name="range_field" label="Interval" required="T" startname="bottom" endname="top" surroundtext="Between %s and %s" ruleequal="F" rulemessage="The top date must be greater than the bottom date" accesskey="I">
			<!-- in the child nodes, you don't need to provide the "name" attribute; the names will be defined by the rangefield -->
			<editfield label="Bottom date" size="12" length="10" mask="DATE"/>
			<editfield label="Top date" size="12" length="10" mask="DATE"/>
		</rangefield>

		<!-- a lookupfield builds an HTML select field based on the values of a database query -->
		<!-- the query string is defined inside the DATASOURCE element -->
		<lookupfield name="lookup_field" label="DB List Box" width="150" help="This is an HTML select box filled by a database query. Click on the List all button to fill the select using JSRS" accesskey="D">
			<datasource>
				<keyfield>client_id</keyfield>
				<displayfield>name</displayfield>
				<lookuptable>client</lookuptable>
				<clause>category = 'Master'</clause>
				<orderby>name</orderby>
			</datasource>
		</lookupfield>

		<!-- this button contains a JSRS event listener, which is a simple tool to perform HTTP requests using JavaScript -->
		<!-- in this special case, we will call a remote function that will bring the complete list of clients, not only the inactive ones -->
		<!-- please open "examples/common/jsrs.php" for more details -->
		<button type="BUTTON" name="fill" value="List all">
			<listener type="JSRS" event="onClick" file="../common/jsrs.php" remote="jsrsTest2" callback="jsrsTest2Return" debug="F"/>
		</button>

		<!-- a combofield builds an HTML select with static options, defined one by one in the XML specification file -->
		<!-- ** the width attribute is the width of the widget in pixels -->
		<combofield name="combo_field" label="List Box" width="100" accesskey="L">
			<option value="M" caption="Male" alt="Click here to choose the male sex"/>
			<option value="F" caption="Female" alt="Click here to choose the female sex"/>
			<!-- an example of a JSRS listener, that allows to call a function from another script when an event is dispatched -->
			<!-- ** the remote attribute is the name of the PHP function to be called -->
			<!-- ** the callback attribute must point to a user JS function, that receives the PHP function return as parameter -->
			<listener type="JSRS" event="onChange" file="../common/jsrs.php" remote="jsrsTest" callback="jsrsTestReturn" params="this.options[this.selectedIndex].text" debug="F"/>
		</combofield>

		<!-- a radiofield builds a group of HTML radio buttons, defined one by one in the XML file -->
		<!-- ** the cols attribute indicates the number of options per line -->
		<radiofield name="radio_field" label="Radio Group" required="T" cols="3">
			<!--
				the radiofield accepts global listeners (direct descendants of radiofield node) or
				individual listeners (descendants of option node). the global listeners will be included
				in the HTML code of all provided options
			-->
			<option value="1" caption="Option 1" alt="Clicking in this option will turn the checkbox check_field mandatory" accesskey="1">
				<listener type="JS" event="onClick" action="alert('option selected: ' + this.value)"/>
			</option>
			<option value="2" caption="Option 2" accesskey="2">
				<listener type="JS" event="onClick" action="alert('option selected: ' + this.value)"/>
			</option>
			<option value="3" caption="Option 3" accesskey="3">
				<!--
					simple demonstration os JS listeners using the CDATA section as the function body
				-->
				<listener type="JS" event="onClick"><![CDATA[
					alert('option selected: ' + element.value);
				]]></listener>
			</option>
		</radiofield>

		<!--
			an example of a check field (CHECKBOX input);
			the checkbox input is renderer together with a hidden field, which name is V_[checkfield_name];
			when the form is submitted, the hidden field's value will be T if the checkbox is checked or F if it's unchecked
		-->
		<checkfield name="check_field" caption="I'm sure I want to click here" accesskey="C">
			<!--
				the following rule will turn the field mandatory if the field "radio field" has the value "1"
				when using this kind of rule, it's recommended to set the attribute "comparetype", to define the data type of the comparison
				the available types are: DATE, INTEGER, FLOAT and STRING
			-->
			<rule type="REQIFEQ" field="radio_field" value="1" comparetype="INTEGER" message="Choosing 'Option 1', the checkbox must be checked!"/>
		</checkfield>

		<!-- here we define a conditional section: its content will not be displayed if the evaluation function returns false -->
		<!-- if you don't define an evaluate function, PHP2Go will search for a function called [section_id]_evaluate() -->
		<!-- finally, if this function isn't defined, the method authorizeFormSection of the default authorizer will be used -->
		<!-- ** you can use procedural functions or static method calls to evaluate section's visibility -->
		<condsection id="condsection" evalfunction="evaluateSection">
			<!--
				a textfield is a simple label; using the default attribute, you can display in the
				label content global variables, request parameters or other dynamic variables;
				to apply values from the global scope, use the pattern ~variable~;
				to evaluate PHP code, use the pattern ~#php code#~
			-->
			<textfield name="remote_addr" label="Remote Addr" default="~REMOTE_ADDR~"/>
			<textfield name="php_text" label="PHP Text" default="Current time: ~#date('H:i:s')#~. This is a dynamic text returned from ~#testFunction()#~!"/>
		</condsection>

		<!-- a memofield is mapped to an HTML input of type "TEXTAREA" -->
		<memofield name="memo_field" label="Textarea" cols="60" rows="6" maxlength="255" charcount="T" accesskey="T">
			<rule type="REQIFEQ" field="combo_field" value="F"/>
		</memofield>

		<!-- a button group -->
		<buttons>
			<!-- a submit button, that is mapped to an HTML input of type "SUBMIT" -->
			<!-- swap the two next lines to see the button with and without images -->
			<button name="submit" type="SUBMIT" value="Submit" accesskey="S"/>
			<!--<button name="submit" type="SUBMIT" img="resources/btn_send.gif" swpimg="resources/btn_send_ovr.gif"/>-->

			<!-- a reset button, that is mapped to an HTML input of type "RESET" -->
			<!-- swap the two next lines to see the button with and without images -->
			<button name="reset" type="RESET" value="Reset"/>
			<!--<button name="reset" type="RESET" img="resources/btn_reset.gif" swpimg="resources/btn_reset_ovr.gif"/>-->

			<!-- a clear button, that builds an input of type "BUTTON" calling a special JavaScript function that clears the form fields -->
			<!-- swap the two next lines to see the button with and without images -->
			<button name="clear" type="CLEAR" value="Clear"/>
			<!--<button name="clear" type="CLEAR" img="resources/btn_clear.gif" swpimg="resources/btn_clear_ovr.gif"/>-->
		</buttons>

	</section>

</form>
